[package]
name = "rust-mq"
version = "0.0.0"
authors = ["metaspacehost@gmail.com"]
edition = "2021"
description = "Integrate message queues."
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
